function New-LocalUserAccountPassword {
  [CmdletBinding()]
  param (
    [Parameter(
      Mandatory = $true,
      Position = 0,
      ValueFromPipelineByPropertyName = $true,
      HelpMessage = "`tA local non-domain Windows account's Username in Bitwarden is an alias for the value of the username in the local SAM database.`n`tLocal usernames follow the format of `"%ComputerName% `$PrimaryGroupID`".`n`tPassword for local user account is obtained by mapping local account username to Bitwarden Username."
    )]
    [ValidatePattern(
      '^[^/\\\[\]\:;\|=,\+\*\?\<\>@"]{1,128}$'
    )]
    [System.String]
    [Alias('bwu')]
    $BitwardenUsername,

    [Parameter(
      Mandatory = $true,
      Position = 1,
      ValueFromPipelineByPropertyName = $true,
      HelpMessage = "FolderId of Item object in Bitwarden Vault. While Bitwarden allows an Item to sit in the 'No Folder' container, this project requires that all Bitwarden Items occupy a Bitwarden Folder."
    )]
    [ValidatePattern(
      '^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$'
    )]
    [ValidateNotNullOrEmpty()]
    [System.String]
    [Alias('fid')]
    $FolderId,

    [Parameter(
      Mandatory = $false, 
      HelpMessage = "Long passwords are impossible to crack when character sequence is generated by a modern cryptographic provider. Length-80 strings are sufficient."
    )]
    [ValidateRange(8,127)]
    [System.UInt32]
    [Alias('len')]
    $PasswordLength = 80,

    [Parameter(
      Mandatory = $false, 
      HelpMessage = "Email address of Bitwarden account. TIP: Use the `$PSDefaultParameterValues automatic variable to avoid repetitive input"
    )]
    [ValidatePattern(
      '^[a-z0-9._%+-]+@(?:[a-z0-9-]+\.)+[a-z]{2,}$'
    )]
    [System.String]
    [Alias('email')]
    $EmailAddressOfBitwardenAccount,

    [Parameter(
      Mandatory = $false, 
      HelpMessage = "Insert the -CheckAuthenticationStatus switch parameter (aliased to -Check) to verify Bitwarden CLI is still authenticated into Bitwarden Account."
    )]
    [System.Management.Automation.SwitchParameter]
    [Alias('Check')]
    $CheckAuthenticationStatus, 

    [Parameter(
      Mandatory = $false, 
      HelpMessage = "Set `$VerboseAuthenticationChecking = `$true to see logic behind decision tree that for confirming that 'status' = 'unlocked'."
    )]
    [System.Boolean]
    [Alias('va')]
    $VerboseAuthenticationChecking = $false, 

    [Parameter(
      Mandatory = $false, 
      HelpMessage = "Set `$VerboseVerification = `$true to see logic behind decision tree that validates user input."
    )]
    [System.Boolean]
    [Alias('vv')]
    $VerboseVerification = $false,

    [Parameter(
      Mandatory = $false, 
      HelpMessage = "Misc notes you can write about this Item into the Bitwarden Account."
    )]
    [AllowEmptyString()]
    [ValidateNotNull()]
    [System.String]
    $Notes = ""
  )

  ${time_Begin New-LocalUserAccountPassword} = [System.DateTime]::Now

  Write-Verbose -Message "Jumping into Set-PrerequisiteConditions from $($PSCmdlet.MyInvocation.InvocationName)"
  Set-PrerequisiteConditions
  Write-Verbose -Message "Returning from Set-PrerequisiteConditions into $($PSCmdlet.MyInvocation.InvocationName)"

  if ($CheckAuthenticationStatus) {
    $HT = @{
      email   = $EmailAddressOfBitwardenAccount
      Verbose = $VerboseAuthenticationChecking
    }
    _CheckBitwardenVaultAuthenticationStatus
  }

  $HT = @{
    ItemLoginUsername = $BitwardenUsername
    FolderId          = $FolderId
    Verbose           = $VerboseVerification
  }
  ${time_Begin _VerifyExactBitwardenItemExistence} = [System.DateTime]::Now
  $IsPresent = _VerifyExactBitwardenItemExistence @HT
  ${time_End _VerifyExactBitwardenItemExistence} = [System.DateTime]::Now
  ${Duration _VerifyExactBitwardenItemExistence} = ${time_End _VerifyExactBitwardenItemExistence} - ${time_Begin _VerifyExactBitwardenItemExistence}

  #region | Exit function if $IsPresent = $true |
  if ($IsPresent) {
    ${time_End New-LocalUserAccountPassword} = [System.DateTime]::Now
    Write-Warning -Message "Exiting function $($PSCmdlet.MyInvocation.InvocationName) because Bitwarden Item with`n  Login.Username = $([System.Char]39)$BitwardenUsername$([System.Char]39)`n    and `$FolderId = $([System.Char]39)$FolderId$([System.Char]39) `n      is already present."
    Write-Warning -Message "`tDuration of '_VerifyExactBitwardenItemExistence':`t  $((${Duration _VerifyExactBitwardenItemExistence}).TotalSeconds.ToString('n3')) Seconds`n"
    #break
  } 
  else {
    Write-Verbose -Message "`tDuration of '_VerifyExactBitwardenItemExistence':`t  $((${Duration _VerifyExactBitwardenItemExistence}).TotalSeconds.ToString('n3')) Seconds`n"
    #region | Item creation after confirmation that $IsPresent = $false |
    #region | Calculate value of Name attribute for the Bitwarden Item |
    Write-Verbose -Message "Initialize new variable for referencing the Name attribute of an Item object in the Bitwarden Vault"
    $_Var_Name = 'Bitwarden Vault Item-Name'
    try {Clear-Variable -Name $_Var_Name -ErrorAction 'Stop'} catch {New-Variable -Name $_Var_Name -Value $null}

    Write-Verbose -Message "Calcualte the first 64 numbers & letters of the SHA-512 hash of `$BitwardenUsername. Convert to lowercase and assign as the Value of this PowerShell variable. "
    ${Bytes UTF8}    = [System.Text.Encoding]::UTF8.GetBytes($BitwardenUsername.ToLower())
    ${Bytes SHA512}  = [System.Security.Cryptography.SHA512CryptoServiceProvider]::New().ComputeHash(${Bytes UTF8})
    $Base64String    = [System.Convert]::ToBase64String(${Bytes SHA512}).ToLower() -replace '\W',''
    Set-Variable -Name $_Var_Name -Value ($Base64String.SubString(0,52))
    #endregion

    Write-Verbose -Message "Initialize new variable for referencing the Username attribute of the Login attribute of an Item object in the Bitwarden Vault"
    $_Var_Name = 'Bitwarden Vault Item-Login.Username'
    try {Clear-Variable -Name $_Var_Name -ErrorAction 'Stop'} catch {New-Variable -Name $_Var_Name -Value $null}

    Write-Verbose -Message "Set that variable value equal to the $BitwardenUsername that the user supplied."
    Set-Variable -Name $_Var_Name -Value ($BitwardenUsername)

    <# ASPIRATIONS |
      1) Code that verifies whether an Item of Username = $BitwardenUsername is already a child object of a specific Folder + child Folders!
      I do NOT want to globally prevent the creation of multiple Item objects with Administrator as the Username. 
      But I DO want to prevent the creation of multiple Item objects with Administrator as the Username within a particular Folder + child Folders!
      Problem for another day... (2025-03-02)

      2) I would like to generate passwords in my Bitwarden account using a CLI and avoid having that password begin existence on my computer! 

      ### Confirming that no such username is already present in the organization. 
      ###     Damn, we should just be searching through the direct child Items in a Folder! 
      ### Query the Bitwarden Organization for an Item object whose Username attribute.  Conceal 'Not Found.' error message emitted from bw.exe by redirecting error stream to variable
      ##$RedirectedErrors = $(
      ##  $BitwardenUsernameInBitwarden = bw.exe get --organizationid ${Bitwarden Organization Id} username "$NetBiosNameOfActiveDirectoryDomain\$SamAccountName"
      ##) 2>&1
      ### exit function if that username is already present
      ##if ($BitwardenUsernameInBitwarden) {
      ##  Write-Warning -Message "`r`n  Active Directory account with username '$BitwardenUsernameInBitwarden' is already present. Attempt:`r`n`tGet-BitwardenPassword -un '$SamAccountName'"
      ##  break
      ##}
    #>

    # Initialize new variable for referencing the Id attribute of a Folder object in the Bitwarden Vault
    #$_Var_Name = 'Bitwarden Vault Folder-Id'
    #try {Clear-Variable -Name $_Var_Name -ErrorAction 'Stop'} catch {New-Variable -Name $_Var_Name -Value $null}

    # Set that variable equal to the Id of the Folder object of focus. 
    #Set-Variable -Name $_Var_Name -Value (bw.exe list folders --search "!msft/ad/$NetBiosNameOfActiveDirectoryDomain" | ConvertFrom-Json | Where-Object {$_.name -match "^!msft/ad/$NetBiosNameOfActiveDirectoryDomain`$"} | Select-Object -ExpandProperty 'id')
    
    Write-Verbose -Message "Generate a password in clear text"
    # --quiet option withholds character sequence from standard output pipeline, and therefore doesn't get saved to variable. 
    $_Var_Name = 'Bitwarden Vault Item-Login.Password In Clear-Text'
    try {Clear-Variable -Name $_Var_Name -ErrorAction 'Stop'} catch {New-Variable -Name $_Var_Name -Value $null}
    Set-Variable -Name $_Var_Name -Value ($(bw.exe generate -lusn --length $PasswordLength))
    # Unless the value is generated non-locally, secure password generation is unavoidable. 
    # For this reason, a *NON-COMPANY* computer for the one-time generation of secure strings in clear text is *STRONGLY* advised. 

    # Initialize a new variable for notes
    $_Var_Name = 'Bitwarden Vault Item-Notes'
    try {Clear-Variable -Name $_Var_Name -ErrorAction 'Stop'} catch {New-Variable -Name $_Var_Name -Value $null}
    Set-Variable -Name $_Var_Name -Value ($Notes)
    
    # Save to separate variables the properties of the object that will eventually be used to define a new Item in Bitwarden Password Manager
    #region | Item Name |
    ${bw item-name}             = '.name="%Bw_Item_Name%"' -replace '%Bw_Item_Name%',${Bitwarden Vault Item-Name}
    #endregion
    #region | Item Login |
    ${bw item-login.username}   = '.login.username="%Bw_Item_Login_Username%"' -replace '%Bw_Item_Login_Username%',${Bitwarden Vault Item-Login.Username}
    ${bw item-login.password}   = '.login.password="%Bw_Item_Login_Password%"' -replace '%Bw_Item_Login_Password%',${Bitwarden Vault Item-Login.Password In Clear-Text}
    #endregion
    #region | Item OrganizationId |
    # ${bw item-organizationId} = '.organizationId="%Id_of_Bw_Org%"' -replace '%Id_of_Bw_Org%',${Bitwarden Organization Id}
    #endregion
    #region | Item Notes |
    if (${Bitwarden Vault Item-Notes}.Length -eq 0) {
      ${bw item-notes} = '.notes="%Item_Notes%"' -replace '%Item_Notes%',""
    }
    else {
      ${bw item-notes} = '.notes="%Item_Notes%"' -replace '%Item_Notes%',${Bitwarden Vault Item-Notes}
    }
    #endregion
    #region | Item FolderID |
    ${bw item-folderId} = '.folderId="%Item_FolderId%"' -replace '%Item_FolderId%',$FolderId
    #endregion  

    Write-Verbose -Message "With the attributes of the Item now saved to variable, write that Item into the Bitwarden Vault."
    bw.exe get template item | jq.exe ${bw item-name} | jq.exe ${bw item-login.username} | jq.exe ${bw item-login.password} | jq.exe ${bw item-notes} | jq.exe ${bw item-folderId} | bw.exe encode | bw.exe create item > $null
    Write-Verbose -Message "Write Operation Complete"

    ${time_End New-LocalUserAccountPassword} = [System.DateTime]::Now
    Write-Verbose -Message "Wait time on username $BitwardenUsername`:`n`t`t$((${time_End New-LocalUserAccountPassword} - ${time_Begin New-LocalUserAccountPassword}).TotalSeconds.ToString('n3')) Seconds`n"
    #endregion
  }
  #endregion
}